//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krkadoni.EnigmaDuplicates.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krkadoni.EnigmaDuplicates.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap channel {
            get {
                object obj = ResourceManager.GetObject("channel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose folder.
        /// </summary>
        internal static string Choose_folder {
            get {
                return ResourceManager.GetString("Choose_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Settings File.
        /// </summary>
        internal static string Choose_Settings_File {
            get {
                return ResourceManager.GetString("Choose_Settings_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete2 {
            get {
                object obj = ResourceManager.GetObject("delete2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates: {0}.
        /// </summary>
        internal static string Duplicates___0_ {
            get {
                return ResourceManager.GetString("Duplicates___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVB-C Services.
        /// </summary>
        internal static string DVB_C_Services {
            get {
                return ResourceManager.GetString("DVB_C_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVB-T Services.
        /// </summary>
        internal static string DVB_T_Services {
            get {
                return ResourceManager.GetString("DVB_T_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load services..
        /// </summary>
        internal static string ERROR_FAILED_SERVICES {
            get {
                return ResourceManager.GetString("ERROR_FAILED_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while looking for duplicates!.
        /// </summary>
        internal static string Error_occured_while_looking_for_duplicates_ {
            get {
                return ResourceManager.GetString("Error_occured_while_looking_for_duplicates_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags: {0}.
        /// </summary>
        internal static string Flags___0_ {
            get {
                return ResourceManager.GetString("Flags___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOUQUETS: {0}{1}.
        /// </summary>
        internal static string FrmDuplicates_UpdateInfoText_Bouquets___0__1_ {
            get {
                return ResourceManager.GetString("FrmDuplicates_UpdateInfoText_Bouquets___0__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available.{0}Please visit {1} to download new version..
        /// </summary>
        internal static string INFO_NEW_VERSION {
            get {
                return ResourceManager.GetString("INFO_NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2013 Krkadoni.com - Released under The MIT License.
        ///
        ///Permission is hereby granted, free of charge, to any person
        ///obtaining a copy of this software and associated documentation
        ///files (the &quot;Software&quot;), to deal in the Software without
        ///restriction, including without limitation the rights to use,
        ///copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the
        ///Software is furnished to do so, subject to the following
        ///conditions:
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No duplicates found! :).
        /// </summary>
        internal static string No_duplicates_found____ {
            get {
                return ResourceManager.GetString("No_duplicates_found____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available. Would you like to download?.
        /// </summary>
        internal static string QUESTION_NEW_VERSION {
            get {
                return ResourceManager.GetString("QUESTION_NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Satellite {
            get {
                object obj = ResourceManager.GetObject("Satellite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved sucessfully!.
        /// </summary>
        internal static string Settings_saved_sucessfully_ {
            get {
                return ResourceManager.GetString("Settings_saved_sucessfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading services.
        /// </summary>
        internal static string STATUS_READING_SERVICES {
            get {
                return ResourceManager.GetString("STATUS_READING_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select services file..
        /// </summary>
        internal static string STATUS_SELECT_SERVICES {
            get {
                return ResourceManager.GetString("STATUS_SELECT_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully removed {0} services!.
        /// </summary>
        internal static string Sucessfully_removed__0__services_ {
            get {
                return ResourceManager.GetString("Sucessfully_removed__0__services_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while matching duplicates with bouquets.
        /// </summary>
        internal static string There_was_an_error_while_matching_duplicates_with_bouquets {
            get {
                return ResourceManager.GetString("There_was_an_error_while_matching_duplicates_with_bouquets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action removes ALL services not used in any Bouquets.{0}Are you sure you want to continue?.
        /// </summary>
        internal static string This_action_removes_not_only_duplicates_but_ALL_services_not_in_any_Bouquets__0_Are_you_sure_you_want_to_continue {
            get {
                return ResourceManager.GetString("This_action_removes_not_only_duplicates_but_ALL_services_not_in_any_Bouquets__0_A" +
                        "re_you_sure_you_want_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0} services, {1} duplicates.{2}{3}.
        /// </summary>
        internal static string Total___0__services___1__duplicates__2__3_ {
            get {
                return ResourceManager.GetString("Total___0__services___1__duplicates__2__3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transponder {
            get {
                object obj = ResourceManager.GetObject("transponder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
